### ISSUE TITLE
system requirement

### ISSUE THREAD

**Issue by cytogenesis** [YanCCscu/MEANGS#4]
hi can you please add information about system requirement in read.me? I tried to run on MacOS but failed, apparently unable to execute binary file nhmmer. I believe it is not compatible with MacOS?

thank you

**Comment by duanyuj** [comment]
Dear Song, I have the same problem. the screenshot as below

/Users/yujieduan/Documents/MEANGS/tools/seqtk trimfq -q 0.01 -l 30 /Users/yujieduan/Documents/MEANGS/DBBX3_1.fq.gz| /Users/yujieduan/Documents/MEANGS/tools/seqtk seq -N -A -Q 33 -q 20 -L 30 - >/Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_1.input.fas
/Users/yujieduan/Documents/MEANGS/tools/seqtk trimfq -q 0.01 -l 30 /Users/yujieduan/Documents/MEANGS/DBBX3_2.fq.gz| /Users/yujieduan/Documents/MEANGS/tools/seqtk seq -N -A -Q 33 -q 20 -L 30 - >/Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_2.input.fas

/bin/sh: /Users/yujieduan/Documents/MEANGS/tools/seqtk: cannot execute binary file
/bin/sh: /Users/yujieduan/Documents/MEANGS/tools/seqtk: cannot execute binary file
/bin/sh: /Users/yujieduan/Documents/MEANGS/tools/seqtk: cannot execute binary file
/bin/sh: /Users/yujieduan/Documents/MEANGS/tools/seqtk: cannot execute binary file
Error occured when running command:
/Users/yujieduan/Documents/MEANGS/tools/seqtk trimfq -q 0.01 -l 30 /Users/yujieduan/Documents/MEANGS/DBBX3_1.fq.gz| /Users/yujieduan/Documents/MEANGS/tools/seqtk seq -N -A -Q 33 -q 20 -L 30 - >/Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_1.input.fas
Error occured when running command:
/Users/yujieduan/Documents/MEANGS/tools/seqtk trimfq -q 0.01 -l 30 /Users/yujieduan/Documents/MEANGS/DBBX3_2.fq.gz| /Users/yujieduan/Documents/MEANGS/tools/seqtk seq -N -A -Q 33 -q 20 -L 30 - >/Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_2.input.fas
2023-04-20 23:04:23
2023-04-20 23:04:23
/Users/yujieduan/Documents/MEANGS/tools/nhmmer -o /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_1_hmmout --tblout /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_1_hmmout_tbl --cpu 8 /Users/yujieduan/Documents/MEANGS/tools/CDS_HMM/Arthropoda_CDS.hmm /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_1.input.fas
/Users/yujieduan/Documents/MEANGS/tools/nhmmer -o /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_2_hmmout --tblout /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_2_hmmout_tbl --cpu 8 /Users/yujieduan/Documents/MEANGS/tools/CDS_HMM/Arthropoda_CDS.hmm /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_2.input.fas


/bin/sh: /Users/yujieduan/Documents/MEANGS/tools/nhmmer: cannot execute binary file
/bin/sh: /Users/yujieduan/Documents/MEANGS/tools/nhmmer: cannot execute binary file
Error occured when running command:
/Users/yujieduan/Documents/MEANGS/tools/nhmmer -o /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_1_hmmout --tblout /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_1_hmmout_tbl --cpu 8 /Users/yujieduan/Documents/MEANGS/tools/CDS_HMM/Arthropoda_CDS.hmm /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_1.input.fas
Error occured when running command:
/Users/yujieduan/Documents/MEANGS/tools/nhmmer -o /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_2_hmmout --tblout /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_2_hmmout_tbl --cpu 8 /Users/yujieduan/Documents/MEANGS/tools/CDS_HMM/Arthropoda_CDS.hmm /Users/yujieduan/Documents/MEANGS/DBBX3/DBBX3_2.input.fas
Traceback (most recent call last):
  File "/Users/yujieduan/Documents/MEANGS/./meangs.py", line 182, in <module>
    mitoReads_withdraw(args.outBase,seqtk,args.outBase+"_1"+"_hmmout_tbl",\
  File "/Users/yujieduan/Documents/MEANGS/./meangs.py", line 94, in mitoReads_withdraw
    with open(tbl) as hmmtbl:

**Comment by Songmh-2020** [comment]
Hi @duanyuj,
Thank you for you providing such content. I think the MEANGS did not work even at the initial step as I saw that the seqtk did not work either. Do you use MacOS either?
I would like to suggest you to have try to install it following the section "Download and Install" or use conda to install it.
Please tell me whether MEANGS works or not?

Thank you for you use.
And we will try to fix the compatible problem of MEANGS

**Comment by duanyuj** [comment]
The conda also not supports Mac M1, and I ran it by docker, “docker run -it --rm -w /home/meangs -v $PWD:/home/meangs bioinfodocker/meangs:latest”, in which /home/meangs means the path in local working directory？

**Comment by webbrain-one** [comment]
Thanks for flagging this! I’ve opened [PR #22](https://github.com/YanCCscu/MEANGS/pull/22) to address it by adding system requirements to the README and fixing the macOS `nhmmer` execution issue.
